services:
  - type: web
    name: brandstack-pdf-importer
    env: node
    plan: free
    buildCommand: |
      npm install
    startCommand: |
      apt-get update && apt-get install -y graphicsmagick ghostscript && node server.js